name: widgetbook_workspace
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.9.2

dependencies:
  flutter:
    sdk: flutter
  design_system:
    path: ../design_system
  papaya_racing:
    path: ../papaya_racing
  widgetbook_annotation: ^3.7.0
  widgetbook: ^3.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner:
  widgetbook_generator: ^3.18.0

flutter:
  uses-material-design: true
